// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDp_d4l9ao3LgTB3CiBdUmZY9GiaOLgvFA',
    appId: '1:9586644686:web:54be8ad3c78c038f13a29f',
    messagingSenderId: '9586644686',
    projectId: 'insta-clone-193b3',
    authDomain: 'insta-clone-193b3.firebaseapp.com',
    storageBucket: 'insta-clone-193b3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdIbYCPRn645DeEPdY6i0c6HRfNmBVjK8',
    appId: '1:9586644686:android:3a7d2a8d2581bb0913a29f',
    messagingSenderId: '9586644686',
    projectId: 'insta-clone-193b3',
    storageBucket: 'insta-clone-193b3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBO44U46wtQccdDPtvCfmOdrkGg8_286ac',
    appId: '1:9586644686:ios:61948abd9c6ada9a13a29f',
    messagingSenderId: '9586644686',
    projectId: 'insta-clone-193b3',
    storageBucket: 'insta-clone-193b3.appspot.com',
    iosClientId: '9586644686-574q875ppjqc0aqs56hluqd7r8e2ppcq.apps.googleusercontent.com',
    iosBundleId: 'com.example.instaClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBO44U46wtQccdDPtvCfmOdrkGg8_286ac',
    appId: '1:9586644686:ios:61948abd9c6ada9a13a29f',
    messagingSenderId: '9586644686',
    projectId: 'insta-clone-193b3',
    storageBucket: 'insta-clone-193b3.appspot.com',
    iosClientId: '9586644686-574q875ppjqc0aqs56hluqd7r8e2ppcq.apps.googleusercontent.com',
    iosBundleId: 'com.example.instaClone',
  );
}
